id = "skript"
name = "Skript"
version = "0.1.3"
schema_version = 1
authors = ["Raze <raze.crs@proton.me>"]
description = "Elite Skript development for Zed."
repository = "https://github.com/razecrs/skript-zed"

[language_servers.skript-lsp]
name = "Skript LSP"
languages = ["Skript"]
